import { chromium } from 'playwright-core'
const b = await chromium.launch({ args: ['--use-gl=angle','--enable-webgl','--ignore-gpu-blocklist'] })
const p = await b.newPage({ viewport: { width: 1700, height: 1050 } })
const errs = []; p.on('pageerror', e => errs.push(String(e)))
const S = '/tmp/claude-0/-home-fabio-quagg-page/589a05f7-f842-4052-beae-d681d0a95b67/scratchpad'
await p.goto('http://localhost:3001/tools/flood-3d?case=Test', { waitUntil: 'networkidle' })
await p.waitForTimeout(2500)
await p.getByText('Ergebnis', { exact: true }).first().click()
await p.waitForTimeout(3500)
await p.locator('input[type=checkbox]').first().check({ force: true }).catch(()=>{})
await p.waitForTimeout(3000)
await p.locator('.f3d-tab', { hasText: 'Grundriss' }).click()
await p.waitForTimeout(6000)
const zeit = p.locator('input[type=range]').last()
const zb = await zeit.boundingBox()
await p.mouse.click(zb.x + zb.width - 4, zb.y + zb.height/2)
await p.waitForTimeout(4000)
await p.locator('.f3d-ctl-group', { hasText: 'Raster' }).locator('select').first().selectOption('tau')
await p.waitForTimeout(3000)
await p.locator('.f3d-hilfe-knopf').first().click()
await p.waitForTimeout(1200)
const box = await p.locator('.f3d-hilfe-karte').boundingBox()
console.log('Karte:', box && `${Math.round(box.x)},${Math.round(box.y)} ${Math.round(box.width)}x${Math.round(box.height)}`)
await p.screenshot({ path: S + '/f3d_hilfe2.png' })
console.log('errors:', errs.length ? errs.slice(0,3) : 'keine')
await b.close()
