// Vorlagen für "Neu anlegen" im Objektbaum (Katalog Spez. 6.2/6.3) und
// deutsche Typbezeichner. Die IDs werden beim Einfügen durchnummeriert.

export const TYPE_LABELS = {
  channel_carve: 'Gerinne einschneiden', pad: 'Planum', raise_lower: 'Anheben/Absenken',
  smooth: 'Glätten', ramp: 'Rampe', embankment: 'Dammschüttung',
  replace_region: 'Bereich ersetzen', set_level: 'Absoluthöhe',
  wall: 'Wand', screen: 'Rechen', culvert: 'Durchlass', weir: 'Wehr',
  pier: 'Pfeiler', basin: 'Becken', imported: 'Importkörper',
  box: 'Box', surface: 'Fläche',
  inflow_hydrograph: 'Zufluss (Ganglinie)', inflow_constant: 'Zufluss (konstant)',
  outflow_fixed_level: 'Ablauf (fester Pegel)', outflow_free: 'Ablauf (frei)',
  atmosphere: 'Atmosphäre',
  discharge_ratio: 'Abflussaufteilung', max_level: 'Max. Einstau',
  max_force: 'Max. Bauteillast', min_bed_shear: 'Min. Sohlschubspannung',
  head_difference: 'Verlusthöhe',
}

export const TEMPLATES = {
  terrain_op: {
    'Gerinne einschneiden': {
      id: 'gerinne', type: 'channel_carve', polyline: [[10, 10], [30, 10]],
      invert_start: 94.5, invert_end: 94.3, bottom_width: 2.0, depth: 1.5,
      side_slope: 1.5,
    },
    Planum: { id: 'planum', type: 'pad',
      polygon: [[10, 10], [20, 10], [20, 20], [10, 20]], level: 95.0 },
    'Anheben/Absenken': { id: 'huegel', type: 'raise_lower',
      center: [15, 15], radius: 5, strength: 1.0, falloff: 'smooth' },
    Glätten: { id: 'glatt', type: 'smooth', center: [15, 15], radius: 5,
      strength: 0.8 },
    Rampe: { id: 'rampe', type: 'ramp',
      polygon: [[10, 10], [20, 10], [20, 14], [10, 14]],
      level_start: 94.5, level_end: 95.5, direction: [1, 0] },
    Dammschüttung: { id: 'damm', type: 'embankment',
      polyline: [[10, 10], [30, 10]], crest_level: 97.0, crest_width: 2.0,
      side_slope: 2.0 },
    Absoluthöhe: { id: 'hoehe', type: 'set_level',
      polygon: [[10, 10], [20, 10], [20, 20], [10, 20]], level: 95.0,
      blend_width: 2.0 },
  },
  structure: {
    Wand: { id: 'wand', type: 'wall', patch: 'wand',
      alignment: { kind: 'polyline', points: [[10, 10, 97.0], [16, 10, 97.0]] },
      height: 2.0, thickness: 0.4 },
    Becken: { id: 'becken', type: 'basin', patch: 'becken',
      footprint: [[10, 10], [16, 10], [16, 16], [10, 16]],
      invert_level: 94.5, wall_height: 2.0, wall_thickness: 0.3 },
    Durchlass: { id: 'durchlass', type: 'culvert', patch: 'durchlass',
      axis: [[8, 12, 94.2], [16, 12, 94.0]],
      profile: { kind: 'circular', diameter: 1.0 } },
    Rechen: { id: 'rechen', type: 'screen', patch: 'rechen',
      plane_polygon: [[10, 10, 94.0], [10, 13, 94.0], [10, 13, 96.5], [10, 10, 96.5]],
      bar_spacing: 0.02, bar_thickness: 0.008, bar_depth: 0.06,
      bar_shape: 'rechteck', approach_angle_deg: 75,
      // d/f leer lassen -> Widerstand wird aus Stabform nach Kirschmer abgeleitet
      resistance: { model: 'darcy_forchheimer', d: [0, 0, 0], f: [0, 0, 0],
        blockage_ratio: 0.3 } },
    'Wehr (Trapez)': { id: 'wehr', type: 'weir', patch: 'wehr',
      crest_polyline: [[10, 10, 96.0], [16, 10, 96.0]],
      crest_width: 0.6, slope_upstream: 2.0, slope_downstream: 2.0,
      profile_type: 'trapez', base_level: 94.0 },
    'Wehr (rundkronig)': { id: 'wehr', type: 'weir', patch: 'wehr',
      crest_polyline: [[10, 10, 96.0], [16, 10, 96.0]],
      crest_width: 0.8, slope_upstream: 1.0, slope_downstream: 2.0,
      profile_type: 'rundkronig', base_level: 94.0 },
    'Pfeiler (Polygon)': { id: 'pfeiler', type: 'pier', patch: 'pfeiler',
      shape: 'polygon',
      footprint: [[12, 12], [13, 12], [13, 14], [12, 14]],
      base_level: 93.0, top_level: 97.0 },
    'Pfeiler (rund)': { id: 'pfeiler', type: 'pier', patch: 'pfeiler',
      shape: 'rund', center: [12, 12], width: 1.2,
      rotation_deg: 0, base_level: 93.0, top_level: 97.0 },
    'Pfeiler (Tropfen)': { id: 'pfeiler', type: 'pier', patch: 'pfeiler',
      shape: 'tropfen', center: [12, 12], width: 1.0, length: 3.0,
      rotation_deg: 0, base_level: 93.0, top_level: 97.0 },
  },
  refinement: {
    Verfeinerungsbox: { id: 'box', type: 'box',
      extent: [10, 10, 93.0, 20, 20, 97.0], level: 2 },
    Flächenverfeinerung: { id: 'flaeche', type: 'surface', target: '', level: 2 },
  },
  boundary: {
    'Zufluss (konstant)': { id: 'zufluss', type: 'inflow_constant',
      patch: 'inlet2', q: 1.0 },
    'Zufluss (Ganglinie)': { id: 'zugang', type: 'inflow_hydrograph',
      patch: 'inlet2', source: 'zufluss.csv', column_time: 't', column_q: 'Q' },
    'Ablauf (fester Pegel)': { id: 'ablauf', type: 'outflow_fixed_level',
      patch: 'outlet2', level: 94.5 },
    'Ablauf (frei)': { id: 'frei', type: 'outflow_free', patch: 'outlet2' },
  },
  section: {
    Querschnitt: { id: 'qs', polyline: [[10, 5], [10, 15]] },
  },
  gauge: {
    Pegelpunkt: { id: 'pegel', point: [12, 12] },
  },
  target: {
    'Max. Einstau': { id: 'einstau', kind: 'max_level', at: '', limit_max: 96.0 },
    Abflussaufteilung: { id: 'aufteilung', kind: 'discharge_ratio',
      of: '', to: '', limit_max: 0.35 },
    'Max. Bauteillast': { id: 'last', kind: 'max_force', at: '',
      component: 'magnitude' },
  },
}
