-- 003_seed_skr04.sql — GENERIERT aus core/skr04.py (cli.py skr04-sql).
-- Nicht von Hand editieren; Aenderungen in skr04.py, dann neu erzeugen.

INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('0135', 'EDV-Software', 'AKTIV') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('0650', 'Bueroeinrichtung', 'AKTIV') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('0670', 'Geringwertige Wirtschaftsgueter', 'AKTIV') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('1200', 'Forderungen aus Lieferungen und Leistungen', 'FORDERUNG') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('1401', 'Abziehbare Vorsteuer 7 %', 'STEUER') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('1406', 'Abziehbare Vorsteuer 19 %', 'STEUER') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('1460', 'Geldtransit', 'FINANZ') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('1550', 'Forderungen gegen Gesellschafter', 'FORDERUNG') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('1600', 'Kasse', 'FINANZ') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('1800', 'Bank', 'FINANZ') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('2900', 'Gezeichnetes Kapital', 'KAPITAL') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('3300', 'Verbindlichkeiten aus Lieferungen und Leistungen', 'VERBINDLICHKEIT') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('3530', 'Verbindlichkeiten gegenueber Gesellschaftern', 'VERBINDLICHKEIT') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('3801', 'Umsatzsteuer 7 %', 'STEUER') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('3806', 'Umsatzsteuer 19 %', 'STEUER') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('3820', 'Umsatzsteuer-Vorauszahlungen', 'STEUER') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('4200', 'Erloese', 'ERTRAG') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('4400', 'Erloese 19 % USt', 'ERTRAG') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('4830', 'Sonstige betriebliche Ertraege', 'ERTRAG') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('5900', 'Fremdleistungen', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6220', 'Abschreibungen auf Sachanlagen', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6260', 'Sofortabschreibung geringwertiger Wirtschaftsgueter', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6310', 'Miete', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6325', 'Gas, Strom, Wasser', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6400', 'Versicherungen', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6420', 'Beitraege (Kammer, Verbaende)', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6600', 'Werbekosten', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6640', 'Bewirtungskosten', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6650', 'Reisekosten Arbeitnehmer', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6670', 'Reisekosten Unternehmer', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6800', 'Porto', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6805', 'Telefon', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6810', 'Telefax und Internetkosten', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6815', 'Buerobedarf', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6820', 'Zeitschriften, Buecher (Fachliteratur)', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6821', 'Fortbildungskosten', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6825', 'Rechts- und Beratungskosten', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6827', 'Abschluss- und Pruefungskosten', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6830', 'Buchfuehrungskosten', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6845', 'Werkzeuge und Kleingeraete', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6850', 'Sonstiger Betriebsbedarf', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('6855', 'Nebenkosten des Geldverkehrs', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('7310', 'Zinsen und aehnliche Aufwendungen', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('7600', 'Koerperschaftsteuer', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('7610', 'Gewerbesteuer', 'AUFWAND') ON CONFLICT (kontonr) DO NOTHING;
INSERT INTO konten (kontonr, bezeichnung, kontoart) VALUES ('9000', 'Saldenvortraege Sachkonten', 'STATISTIK') ON CONFLICT (kontonr) DO NOTHING;
